name: V8 Ignition Build and Test

on:
  push:
    branches: [ main ]
    paths:
      - 'src/compiler/**'
      - 'src/ignition/**'
      - 'test/ignition/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/compiler/**'
      - 'src/ignition/**'
      - 'test/ignition/**'
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and Test Ignition
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip pkg-config libglib2.0-dev
        sudo pip3 install ninja
        
    - name: Setup depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH
    
    - name: Fetch V8 dependencies
      run: |
        gclient config https://chromium.googlesource.com/v8/v8
        gclient sync
    
    - name: Configure V8 build (Ignition only)
      run: |
        cd v8
        gn gen out/ignition --args='is_debug=false v8_enable_turbofan=false v8_enable_sparkplug=false v8_enable_maglev=false v8_enable_webassembly=false is_component_build=true v8_monolithic=false v8_use_external_startup_data=false v8_enable_i18n_support=false target_cpu="x64"'
    
    - name: Build V8 Ignition
      run: |
        cd v8
        ninja -C out/ignition v8_monolith
    
    - name: Run Ignition unit tests
      run: |
        cd v8
        python3 tools/run-tests.py --outdir=out/ignition ignition unittests

    - name: Run Ignition integration tests
      run: |
        cd v8
        python3 tools/run-tests.py --outdir=out/ignition ignition mjsunit/ignition
    
    - name: Run Ignition performance tests
      run: |
        cd v8
        python3 tools/run-tests.py --outdir=out/ignition ignition benchmarks/ignition
    
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ignition-test-results
        path: |
          v8/out/ignition/test-results
          v8/out/ignition/*.log
